separators:
    struct: "."
    arrayBegin: "["
    arrayEnd: "]"

comparators:
    "==": EQUALS
    "=": EQUALS
    EQUALS: EQUALS
    "!=": NOT
    NOT: NOT
    GREATER: GREATER
    LESS: LESS
    LESS_EQUAL: LESS_EQUAL
    GREATER_EQUAL: GREATER_EQUAL
    ">": GREATER
    "<": LESS
    "<=": LESS_EQUAL
    ">=": GREATER_EQUAL

# You can set XML Tags o use for a name
# and define default values
# Specify required values and optional (possible for better syntax checks later)

# This is for start, events, event prototypes to translate 
# sections tinto xml tags
tagDefaults:
    relative_position: 
        tag: set_relative_position
        # Maybe this a way to have deeper validation
        required: 
            - name1
            - name2
            - distance
            - angle

    # Allow generic create
    create:
        tag: create

    terrain:
        _section: true
        nebulas:
            tag: create
            defaults: 
                type: nebulas
        asteroids:
            tag: create
            defaults: 
                type: asteroids
        mines:
            tag: create
            defaults: 
                type: mines
                
    monsters:
        _section: true
        typhons:
            tag: create
            defaults: 
                type: monster
                monsterType: 0
        whales:
            tag: create
            defaults: 
                type: monster
                monsterType: 1
        sharks:
            tag: create
            defaults: 
                type: monster
                monsterType: 2
        dragons:
            tag: create
            defaults: 
                type: monster
                monsterType: 3
        piras:
            tag: create
            defaults: 
                type: monster
                monsterType: 4
        charybdis:
            tag: create
            defaults: 
                type: monster
                monsterType: 5
        nsect:
            tag: create
            defaults: 
                type: monster
                monsterType: 6
        insect:
            tag: create
            defaults: 
                type: monster
                monsterType: 6
        jelly:
            tag: create
            defaults: 
                type: monster
                monsterType: 7
        wreck:
            tag: create
            defaults: 
                type: monster
                monsterType: 8

    anomalies:
        tag: create
        defaults: 
            type: anomaly


    beacons:
        _section: true
        typhons:
            tag: create
            defaults: 
                type: anomaly
                beaconMonsterType: 0
        whales:
            tag: create
            defaults: 
                type: anomaly
                beaconMonsterType: 1
        sharks:
            tag: create
            defaults: 
                type: anomaly
                beaconMonsterType: 2
        dragons:
            tag: create
            defaults: 
                type: anomaly
                beaconMonsterType: 3
        piras:
            tag: create
            defaults: 
                type: monster
                beaconMonsterType: 4
        charybdis:
            tag: create
            defaults: 
                type: anomaly
                beaconMonsterType: 5
        nsect:
            tag: create
            defaults: 
                type: anomaly
                monsterType: 6
        insect:
            tag: create
            defaults: 
                type: anomaly
                beaconMonsterType: 6
        jelly:
            tag: create
            defaults: 
                type: anomaly
                beaconMonsterType: 7
        wreck:
            tag: create
            defaults: 
                type: anomaly
                beaconMonsterType: 8

# conditions are arrays of mixed type
    conditions:
        _collection: true

# The elements that are locked for in an import
valid-imports:
    - start
    - events
    - event_prototypes
    - prototypes
    - ranges

